name: Claude Code Review

on:
  pull_request:
    types: [labeled]

jobs:
  claude-review:
    if: github.event.label.name == 'claude-review'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure git credentials for marketplace
        run: |
          git config --global url."https://x-access-token:${{ secrets.TUPI_AI_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          plugin_marketplaces: |
              https://github.com/tupinamba-energia/tupi-ai.git
          plugins: |
            engineering@tupi-ai
          prompt: |
            Review PR #${{ github.event.pull_request.number }} in ${{ github.repository }}

            Use the `engineering:code-review-guidelines` skill for review focus areas and feedback format.

            *Steps (follow exactly)*:
            1. Fetch the PR diff using GitHub MCP tools
            2. Add inline comments on specific lines using `mcp__github_inline_comment__create_inline_comment`
            3. Submit review with 2-3 sentence summary (list agents/skills names used as a final note)

            Follow @CLAUDE.md conventions and check engineering plugin agents and skills for best practices and platform knowledge

          # MCP tools for inline PR review + file/code exploration tools + plugin skills
          claude_args: '--model "opus" --allowedTools "Skill,Task,Read,Grep,Glob,mcp__github__get_pull_request,mcp__github__get_pull_request_diff,mcp__github__create_pending_pull_request_review,mcp__github__add_pull_request_review_comment_to_pending_review,mcp__github__submit_pending_pull_request_review,mcp__github_inline_comment__create_inline_comment,mcp__github__create_and_submit_pull_request_review"'
          show_full_output: false # true if need to debug claude reasoning or issues
